// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQKD1RLH1tjiV6HJFyF1P0N-G8Gyg0ZCU',
    appId: '1:253726337825:web:0fdb20670003fba95fec60',
    messagingSenderId: '253726337825',
    projectId: 'mica-community-3798e',
    authDomain: 'mica-community-3798e.firebaseapp.com',
    storageBucket: 'mica-community-3798e.appspot.com',
    measurementId: 'G-88EM8ZTL37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKC7KNOrdYVVPAb8udBTqYr4AJ-f_l0Do',
    appId: '1:253726337825:android:b3a9e6045626c3d95fec60',
    messagingSenderId: '253726337825',
    projectId: 'mica-community-3798e',
    storageBucket: 'mica-community-3798e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN1xRlvIyIWbtEqHvClAuHLVZKi9MCdHQ',
    appId: '1:253726337825:ios:0da95c29f747e5685fec60',
    messagingSenderId: '253726337825',
    projectId: 'mica-community-3798e',
    storageBucket: 'mica-community-3798e.appspot.com',
    iosBundleId: 'com.example.micaCommunity2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN1xRlvIyIWbtEqHvClAuHLVZKi9MCdHQ',
    appId: '1:253726337825:ios:0da95c29f747e5685fec60',
    messagingSenderId: '253726337825',
    projectId: 'mica-community-3798e',
    storageBucket: 'mica-community-3798e.appspot.com',
    iosBundleId: 'com.example.micaCommunity2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQKD1RLH1tjiV6HJFyF1P0N-G8Gyg0ZCU',
    appId: '1:253726337825:web:54874781a640b8ef5fec60',
    messagingSenderId: '253726337825',
    projectId: 'mica-community-3798e',
    authDomain: 'mica-community-3798e.firebaseapp.com',
    storageBucket: 'mica-community-3798e.appspot.com',
    measurementId: 'G-DCVM3VBPHT',
  );
}
